from BiCoder import BiCoder
import tensorflow as tf

class Decoder(BiCoder):
    """
    Probabilistic Decoder p(x|z).

    This class inherits from BiCoder and implements the specific behavior 
    required to generate reconstructed samples (x̂) from the latent variable z.
    
    """

    def __init__(self, decoder):
        """
        Initializes the Decoder instance.

        The constructor calls the superclass constructor (super().__init__()) 
        to define the inherited network structure. 

        Parameters
        decoder : tf.keras.Sequential
            The neural network used to compute the mean (µx) 
            of the reconstructed data distribution from the latent sample z.
        """
        super().__init__(decoder)
        self._sigma = 0.75  #fixed std dev

    def call(self, z):
        """
        Implements the forward pass for the probabilistic decoder pθ(x|z).
        It passes the latent sample z through the network to compute the mean (µx), 
        calculates the fixed log stand.div.,and generates the reconstructed sample using the shared 
        Gaussian sampling method

        Parameters
        z : tf.Tensor
            The latent sample generated by the Encoder or sampled from the prior p(z).

        Returns
        tuple[tf.Tensor, tf.Tensor, tf.Tensor]
            mu_x: The mean (µx) of the reconstructed data distribution.
            log_sigma_x: The logarithm of the fixed standard deviation
                         of the reconstructed distribution.
            x_hat: The reconstructed sample sampled from N(µx, σ²).
        """
        mu_x = self.forward_network(z)
        sigma = tf.constant(self._sigma, dtype=tf.float32)
        log_sigma_x = tf.math.log(self._sigma)
        x_hat = self.sample_gaussian(mu_x, sigma)  #same shared method

        return mu_x, log_sigma_x, x_hat
    
    #Accessor method
    @property
    def fixed_std_dev(self):
        """
        Returns the fixed standard deviation used by the decoder
        when sampling reconstructed outputs.
        """
        return self._sigma

    
    #Mutator method
    @fixed_std_dev.setter
    def fixed_std_dev(self, new_sigma):
         """
        Updates the fixed standard deviation used in the decoder.

        Parameters
        new_sigma : float
            The new standard deviation value to assign.
        """
         self._sigma = new_sigma